# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0f11ef406b247660f47c556a4c1771c944005e9f299d4b690fe3590dfac009494e76d3eecd331a09db60a03d4d019c53dda75a44c9fb7e826fb4a50ce1c5c340

test:
  secret_key_base: 7f1a31d87beecbc9dd881d3e599433f39c89405760e228c1efe48c662e058ab2b542534b12d9d9d35e6325f19fe139f62c2c6ad4ab06ad564952d030fa748a7f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
